---
title: "Earthquake Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: bootstrap
  

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(DT)
library(plotly)
library(dplyr)
library(leaflet)
library(htmltools)
library(knitr)
eqtr <- read.csv(file = "earthquake.csv", header = T, sep = ",", nrows = 1000)
```

Row {data-height=650}
-------------------------------------

### Harita
    
```{r harita, echo=FALSE}
pal <- colorNumeric(
  palette = "YlOrRd",
  domain = eqtr$xm
)

eqtr %>% filter(xm>4.5) %>% leaflet() %>% addTiles() %>% 
  addCircleMarkers(lng = ~long, 
                   lat = ~lat, 
                   fillColor = pal(eqtr$xm),
                   stroke = F,
                   popup = ~htmlEscape(as.character(xm))) %>% 
  addLegend("bottomright", pal = pal, values = ~xm,
    opacity = 1
  )
```

Row {.tabset .tabset-fade}
-------------------------------------

### Tablo
    
```{r readandshow, echo=FALSE}
eqtr <- eqtr %>% subset(select = -c(id,lat,long,md,richter,mw,ms,mb))
eqtr %>% filter(xm>5) %>% datatable(options = list(pageLength = 10))
```
   

### Özet 

```{r summary, echo=FALSE}
eqtr %>% summary()
```   

